/*
 * Main.java
 *
 * Created on 14 Январь 2007 г., 18:39
 */

package ru.spb.ConcreteSoft.tipWindow;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author  mbb
 */
public class Main extends javax.swing.JFrame implements MouseListener {
    static TipWindow tipWindow;
    
    /** Creates new form Main */
    public Main() {
        initComponents();
        addMouseMotionListener(MouseMoveQueue.getInstance());
        tipWindow = new TipWindow();
        tipWindow.setVisible(true);
        addMouseListener(this);
        TipThread tipThread = new TipThread(tipWindow);
        tipThread.start();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel1.setText("jLabel1 loooooooooooooong");
        getContentPane().add(jLabel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void mouseClicked(MouseEvent e) {
    }

    public void mousePressed(MouseEvent e) {
    }

    public void mouseReleased(MouseEvent e) {
    }

    public void mouseEntered(MouseEvent e) {
    }

    public void mouseExited(MouseEvent e) {
//        System.out.println(e.getX());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
